version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: kebunkita-app
    container_name: kebunkita-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - kebun-net
    ports:
      - "9000:9000"

  db:
    image: mysql:8.0
    container_name: kebunkita-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: kebunkita
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: kebun
      MYSQL_PASSWORD: kebunpass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - kebun-net

  nginx:
    image: nginx:stable
    container_name: kebunkita-nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - kebun-net

networks:
  kebun-net:

volumes:
  db_data:
